var items = [
    {id: 'rapi', name: 'Rapi', image: 'images/nikke/fullbody/rapi.png'},
    {id: 'anis', name: 'Anis', image: 'images/nikke/fullbody/anis.png'},
    {id: 'neon', name: 'Neon', image: 'images/nikke/fullbody/neon.png'},

    {id: 'delta', name: 'Delta', image: 'images/nikke/fullbody/delta.png'},
    {id: 'signal', name: 'Signal', image: 'images/nikke/fullbody/signal.png', imageScale: 1.09, imageY: '-2%'},
    {id: 'poli', name: 'Poli', image: 'images/nikke/fullbody/poli.png', imageX: '3%'},
    {id: 'miranda', name: 'Miranda', image: 'images/nikke/fullbody/miranda.png'},
    {id: 'd', name: 'D', image: 'images/nikke/fullbody/d.png'},

    {id: 'belorta', name: 'Belorta', image: 'images/nikke/fullbody/belorta.png'},
    {id: 'mica', name: 'Mica', image: 'images/nikke/fullbody/mica.png'},
    {id: 'brid', name: 'Brid', image: 'images/nikke/fullbody/brid.png', imageScale: 1.28},
    {id: 'soline', name: 'Soline', image: 'images/nikke/fullbody/soline.png'},
    {id: 'diesel', name: 'Diesel', image: 'images/nikke/fullbody/diesel.png'},

    {id: 'centi', name: 'Centi', image: 'images/nikke/fullbody/centi.png'},
    {id: 'liter', name: 'Liter', image: 'images/nikke/fullbody/liter.png'},
    {id: 'emma', name: 'Emma', image: 'images/nikke/fullbody/emma.png'},
    {id: 'vesti', name: 'Vesti', image: 'images/nikke/fullbody/vesti.png'},
    {id: 'eunhwa', name: 'Eunhwa', image: 'images/nikke/fullbody/eunhwa.png', imageScale: 1.05},

    {id: 'laplace', name: 'Laplace', image: 'images/nikke/fullbody/laplace.png', imageScale: 1.05, imageY: '-2%'},
    {id: 'drake', name: 'Drake', image: 'images/nikke/fullbody/drake.png'},
    {id: 'maxwell', name: 'Maxwell', image: 'images/nikke/fullbody/maxwell.png', imageScale: 1.28, imageY: '-2%', imageX: '4%'},
    {id: 'crow', name: 'Crow', image: 'images/nikke/fullbody/crow.png'},
    {id: 'jackal', name: 'Jackal', image: 'images/nikke/fullbody/jackal.png'},
    {id: 'viper', name: 'Viper', image: 'images/nikke/fullbody/viper.png'},
    {id: 'n102', name: 'N102', image: 'images/nikke/fullbody/n102.png'},
    {id: 'anne-miracle-fairy', name: 'Anne: Miracle Fairy', image: 'images/nikke/fullbody/anne-miracle-fairy.png'},
    {id: 'mary', name: 'Mary', image: 'images/nikke/fullbody/mary.png'},
    {id: 'pepper', name: 'Pepper', image: 'images/nikke/fullbody/pepper.png'},
    {id: 'mary-bay-goddess', name: 'Mary: Bay Goddess', image: 'images/nikke/fullbody/mary-bay-goddess.png'},
    {id: 'sugar', name: 'Sugar', image: 'images/nikke/fullbody/sugar.png', imageScale: 1.20},
    {id: 'milk', name: 'Milk', image: 'images/nikke/fullbody/milk.png'},
    {id: 'frima', name: 'Frima', image: 'images/nikke/fullbody/frima.png'},
    {id: 'julia', name: 'Julia', image: 'images/nikke/fullbody/julia.png'},

    {id: 'yuni', name: 'Yuni', image: 'images/nikke/fullbody/yuni.png'},
    {id: 'mihara', name: 'Mihara', image: 'images/nikke/fullbody/mihara.png'},
    {id: 'privaty', name: 'Privaty', image: 'images/nikke/fullbody/privaty.png'},
    {id: 'yulha', name: 'Yulha', image: 'images/nikke/fullbody/yulha.png'},
    {id: 'admi', name: 'Admi', image: 'images/nikke/fullbody/admi.png'},
    {id: 'guillotine', name: 'Guillotine', image: 'images/nikke/fullbody/guillotine.png'},
    {id: 'maiden', name: 'Maiden', image: 'images/nikke/fullbody/maiden.png', imageScale: 1.24, imageX: '-3%'},
    {id: 'ludmilla', name: 'Ludmilla', image: 'images/nikke/fullbody/ludmilla.png', imageX: '5%', imageY: '-2%'},
    {id: 'alice', name: 'Alice', image: 'images/nikke/fullbody/alice.png'},
    {id: 'neve', name: 'Neve', image: 'images/nikke/fullbody/neve.png'},
    {id: 'rupee', name: 'Rupee', image: 'images/nikke/fullbody/rupee.png'},
    {id: 'yan', name: 'Yan', image: 'images/nikke/fullbody/yan.png', imageScale: 1.10},
    {id: 'dolla', name: 'Dolla', image: 'images/nikke/fullbody/dolla.png'},
    {id: 'rupee-winter-shopper', name: 'Rupee: Winter Shopper', image: 'images/nikke/fullbody/rupee-winter-shopper.png', imageScale: 1.27, imageX: '10%', imageY: '2%'},
    {id: 'exia', name: 'Exia', image: 'images/nikke/fullbody/exia.png'},
    {id: 'novel', name: 'Novel', image: 'images/nikke/fullbody/novel.png'},
    {id: 'snow-white', name: 'Snow White', image: 'images/nikke/fullbody/snow-white.png', imageScale: 1.35, imageX: '11%'},
    {id: 'rapunzel', name: 'Rapunzel', image: 'images/nikke/fullbody/rapunzel.png', imageScale: 1.28, imageX: '3%'},
    {id: 'scarlet', name: 'Scarlet', image: 'images/nikke/fullbody/scarlet.png', imageScale: 1.40, imageX: '6%'},
    {id: 'harran', name: 'Harran', image: 'images/nikke/fullbody/harran.png', imageScale: 1.29},

    {id: 'neon-blue-ocean', name: 'Neon: Blue Ocean', image: 'images/nikke/fullbody/neon-blue-ocean.png', imageScale: 1.28, imageX: '4%', imageY: '-3%'},
    {id: 'anis-sparkling-summer', name: 'Anis: Sparkling Summer', image: 'images/nikke/fullbody/anis-sparkling-summer.png'},
    {id: 'isabel', name: 'Isabel', image: 'images/nikke/fullbody/isabel.png', imageScale: 1.75},
    {id: 'noah', name: 'Noah', image: 'images/nikke/fullbody/noah.png', imageScale: 1.22},
    {id: 'dorothy', name: 'Dorothy', image: 'images/nikke/fullbody/dorothy.png'},
    {id: 'rumani', name: 'Rumani', image: 'images/nikke/fullbody/rumani.png'},
    {id: 'epinel', name: 'Epinel', image: 'images/nikke/fullbody/epinel.png'},
    {id: 'folkwang', name: 'Folkwang', image: 'images/nikke/fullbody/folkwang.png'},
    {id: 'modernia', name: 'Modernia', image: 'images/nikke/fullbody/modernia.png', imageScale: 1.20},
    {id: 'nihilister', name: 'Nihilister', image: 'images/nikke/fullbody/nihilister.png', imageScale: 1.42},
    {id: 'blanc', name: 'Blanc', image: 'images/nikke/fullbody/blanc.png', imageScale: 1.05},
    {id: 'noir', name: 'Noir', image: 'images/nikke/fullbody/noir.png'},
    {id: 'rosanna', name: 'Rosanna', image: 'images/nikke/fullbody/rosanna.png'},
    {id: 'sakura', name: 'Sakura', image: 'images/nikke/fullbody/sakura.png'},
    {id: 'ether', name: 'Ether', image: 'images/nikke/fullbody/ether.png', imageScale: 1.08},
    {id: 'soldier-eg', name: 'Soldier EG', image: 'images/nikke/fullbody/soldier-eg.png'},
    {id: 'soldier-fa', name: 'Soldier FA', image: 'images/nikke/fullbody/soldier-fa.png'},
    {id: 'product-08', name: 'Product 08', image: 'images/nikke/fullbody/product-08.png'},
    {id: 'product-12', name: 'Product 12', image: 'images/nikke/fullbody/product-12.png'},
    {id: 'idoll-flower', name: 'iDoll Flower', image: 'images/nikke/fullbody/idoll-flower.png'},

    {id: 'idoll-ocean', name: 'iDoll Ocean', image: 'images/nikke/fullbody/idoll-ocean.png'},
    {id: 'soldier-ow', name: 'Soldier OW', image: 'images/nikke/fullbody/soldier-ow.png'},
    {id: 'product-23', name: 'Product 23', image: 'images/nikke/fullbody/product-23.png'},
    {id: 'idoll-sun', name: 'iDoll Sun', image: 'images/nikke/fullbody/idoll-sun.png'},
    {id: 'cocoa', name: 'Cocoa', image: 'images/nikke/fullbody/cocoa.png'},
    {id: 'soda', name: 'Soda', image: 'images/nikke/fullbody/soda.png'},
    {id: 'mast', name: 'Mast', image: 'images/nikke/fullbody/mast.png', imageScale: 1.10},
    {id: 'anchor', name: 'Anchor', image: 'images/nikke/fullbody/anchor.png'},
    {id: 'helm', name: 'Helm', image: 'images/nikke/fullbody/helm.png', imageScale: 1.10, imageY: '5%', imageX: '2%'},
    {id: 'helm-aquamarine', name: 'Helm: Aquamarine', image: 'images/nikke/fullbody/helm-aquamarine.png', imageScale: 1.02},
    {id: 'nero', name: 'Nero', image: 'images/nikke/fullbody/nero.png'},
    {id: 'biscuit', name: 'Biscuit', image: 'images/nikke/fullbody/biscuit.png'},
    {id: 'rei', name: 'Rei', image: 'images/nikke/fullbody/rei.png', imageScale: 1.18},
    {id: 'guilty', name: 'Guilty', image: 'images/nikke/fullbody/guilty.png'},
    {id: 'sin', name: 'Sin', image: 'images/nikke/fullbody/sin.png'},
    {id: 'quency', name: 'Quency', image: 'images/nikke/fullbody/quency.png'},
    {id: 'noise', name: 'Noise', image: 'images/nikke/fullbody/noise.png'},
    {id: 'volume', name: 'Volume', image: 'images/nikke/fullbody/volume.png', imageScale: 1.08},
    {id: 'aria', name: 'Aria', image: 'images/nikke/fullbody/aria.png'},
    {id: 'makima', name: 'Makima', image: 'images/nikke/fullbody/makima.png'}
];
