var items = [
    {id: 'rapi', name: 'Rapi', image: 'images/nikke/fullbody/rapi.png'},
    {id: 'anis', name: 'Anis', image: 'images/nikke/fullbody/anis.png'},
    {id: 'neon', name: 'Neon', image: 'images/nikke/fullbody/neon.png'},

    {id: 'delta', name: 'Delta', image: 'images/nikke/fullbody/delta.png'},
    {id: 'signal', name: 'Signal', image: 'images/nikke/fullbody/signal.png', imageScale: 1.09, imageY: '-2%'},
    {id: 'poli', name: 'Poli', image: 'images/nikke/fullbody/poli.png', imageX: '3%'},
    {id: 'miranda', name: 'Miranda', image: 'images/nikke/fullbody/miranda.png'},
    {id: 'd', name: 'D', image: 'images/nikke/fullbody/d.png'},

    {id: 'belorta', name: 'Belorta', image: 'images/nikke/fullbody/belorta.png'},
    {id: 'mica', name: 'Mica', image: 'images/nikke/fullbody/mica.png'},
    {id: 'brid', name: 'Brid', image: 'images/nikke/fullbody/brid.png', imageScale: 1.28},
    {id: 'soline', name: 'Soline', image: 'images/nikke/fullbody/soline.png'},
    {id: 'diesel', name: 'Diesel', image: 'images/nikke/fullbody/diesel.png'},

    {id: 'centi', name: 'Centi', image: 'images/nikke/fullbody/centi.png'},
    {id: 'liter', name: 'Liter', image: 'images/nikke/fullbody/liter.png'},
    {id: 'emma', name: 'Emma', image: 'images/nikke/fullbody/emma.png'},
    {id: 'vesti', name: 'Vesti', image: 'images/nikke/fullbody/vesti.png'},
    {id: 'eunhwa', name: 'Eunhwa', image: 'images/nikke/fullbody/eunhwa.png', imageScale: 1.05},

    {id: 'laplace', name: 'Laplace', image: 'images/nikke/fullbody/laplace.png', imageScale: 1.05, imageY: '-2%'},
    {id: 'drake', name: 'Drake', image: 'images/nikke/fullbody/drake.png'},
    {id: 'maxwell', name: 'Maxwell', image: 'images/nikke/fullbody/maxwell.png', imageScale: 1.28, imageY: '-2%', imageX: '4%'},
    {id: 'crow', name: 'Crow', image: 'images/nikke/fullbody/crow.png'},
    {id: 'jackal', name: 'Jackal', image: 'images/nikke/fullbody/jackal.png'},
    {id: 'viper', name: 'Viper', image: 'images/nikke/fullbody/viper.png'},
    {id: 'n102', name: 'N102', image: 'images/nikke/fullbody/n102.png'},
    {id: 'anne-miracle-fairy', name: 'Anne: Miracle Fairy', image: 'images/nikke/fullbody/anne-miracle-fairy.png'},
    {id: 'mary', name: 'Mary', image: 'images/nikke/fullbody/mary.png'},
    {id: 'pepper', name: 'Pepper', image: 'images/nikke/fullbody/pepper.png'},
    {id: 'mary-bay-goddess', name: 'Mary: Bay Goddess', image: 'images/nikke/fullbody/mary-bay-goddess.png'},
    {id: 'sugar', name: 'Sugar', image: 'images/nikke/fullbody/sugar.png', imageScale: 1.20},
    {id: 'milk', name: 'Milk', image: 'images/nikke/fullbody/milk.png'},
    {id: 'frima', name: 'Frima', image: 'images/nikke/fullbody/frima.png'},
    {id: 'julia', name: 'Julia', image: 'images/nikke/fullbody/julia.png'},

    {id: 'yuni', name: 'Yuni', image: 'images/nikke/fullbody/yuni.png'},
    {id: 'mihara', name: 'Mihara', image: 'images/nikke/fullbody/mihara.png'},
    {id: 'privaty', name: 'Privaty', image: 'images/nikke/fullbody/privaty.png'},
    {id: 'yulha', name: 'Yulha', image: 'images/nikke/fullbody/yulha.png'},
    {id: 'admi', name: 'Admi', image: 'images/nikke/fullbody/admi.png'},
    {id: 'guillotine', name: 'Guillotine', image: 'images/nikke/fullbody/guillotine.png'},
    {id: 'maiden', name: 'Maiden', image: 'images/nikke/fullbody/maiden.png', imageScale: 1.24, imageX: '-3%'},
    {id: 'ludmilla', name: 'Ludmilla', image: 'images/nikke/fullbody/ludmilla.png', imageX: '5%', imageY: '-2%'},
    {id: 'alice', name: 'Alice', image: 'images/nikke/fullbody/alice.png'},
    {id: 'neve', name: 'Neve', image: 'images/nikke/fullbody/neve.png'},
    {id: 'rupee', name: 'Rupee', image: 'images/nikke/fullbody/rupee.png'},
    {id: 'yan', name: 'Yan', image: 'images/nikke/fullbody/yan.png', imageScale: 1.10},
    {id: 'dolla', name: 'Dolla', image: 'images/nikke/fullbody/dolla.png'},
    {id: 'rupee-winter-shopper', name: 'Rupee: Winter Shopper', image: 'images/nikke/fullbody/rupee-winter-shopper.png', imageScale: 1.27, imageX: '10%', imageY: '2%'},
    {id: 'exia', name: 'Exia', image: 'images/nikke/fullbody/exia.png'},
    {id: 'novel', name: 'Novel', image: 'images/nikke/fullbody/novel.png'},
    {id: 'snow-white', name: 'Snow White', image: 'images/nikke/fullbody/snow-white.png', imageScale: 1.35, imageX: '11%'},
    {id: 'rapunzel', name: 'Rapunzel', image: 'images/nikke/fullbody/rapunzel.png', imageScale: 1.28, imageX: '3%'},
    {id: 'scarlet', name: 'Scarlet', image: 'images/nikke/fullbody/scarlet.png', imageScale: 1.40, imageX: '6%'},
    {id: 'harran', name: 'Harran', image: 'images/nikke/fullbody/harran.png', imageScale: 1.29},

    {id: 'neon-blue-ocean', name: 'Neon: Blue Ocean', image: 'images/nikke/fullbody/neon-blue-ocean.png', imageScale: 1.28, imageX: '4%', imageY: '-3%'},
    {id: 'anis-sparkling-summer', name: 'Anis: Sparkling Summer', image: 'images/nikke/fullbody/anis-sparkling-summer.png'},
    {id: 'isabel', name: 'Isabel', image: 'images/nikke/fullbody/isabel.png', imageScale: 1.75},
    {id: 'noah', name: 'Noah', image: 'images/nikke/fullbody/noah.png', imageScale: 1.22},
    {id: 'dorothy', name: 'Dorothy', image: 'images/nikke/fullbody/dorothy.png'},
    {id: 'rumani', name: 'Rumani', image: 'images/nikke/fullbody/rumani.png'},
    {id: 'epinel', name: 'Epinel', image: 'images/nikke/fullbody/epinel.png'},
    {id: 'folkwang', name: 'Folkwang', image: 'images/nikke/fullbody/folkwang.png'},
    {id: 'modernia', name: 'Modernia', image: 'images/nikke/fullbody/modernia.png', imageScale: 1.20},
    {id: 'nihilister', name: 'Nihilister', image: 'images/nikke/fullbody/nihilister.png', imageScale: 1.42},
    {id: 'blanc', name: 'Blanc', image: 'images/nikke/fullbody/blanc.png', imageScale: 1.05},
    {id: 'noir', name: 'Noir', image: 'images/nikke/fullbody/noir.png'},
    {id: 'rosanna', name: 'Rosanna', image: 'images/nikke/fullbody/rosanna.png'},
    {id: 'sakura', name: 'Sakura', image: 'images/nikke/fullbody/sakura.png'},
    {id: 'ether', name: 'Ether', image: 'images/nikke/fullbody/ether.png', imageScale: 1.08},
    {id: 'soldier-eg', name: 'Soldier EG', image: 'images/nikke/fullbody/soldier-eg.png'},
    {id: 'soldier-fa', name: 'Soldier FA', image: 'images/nikke/fullbody/soldier-fa.png'},
    {id: 'product-08', name: 'Product 08', image: 'images/nikke/fullbody/product-08.png'},
    {id: 'product-12', name: 'Product 12', image: 'images/nikke/fullbody/product-12.png'},
    {id: 'idoll-flower', name: 'iDoll Flower', image: 'images/nikke/fullbody/idoll-flower.png'},

    {id: 'idoll-ocean', name: 'iDoll Ocean', image: 'images/nikke/fullbody/idoll-ocean.png'},
    {id: 'soldier-ow', name: 'Soldier OW', image: 'images/nikke/fullbody/soldier-ow.png'},
    {id: 'product-23', name: 'Product 23', image: 'images/nikke/fullbody/product-23.png'},
    {id: 'idoll-sun', name: 'iDoll Sun', image: 'images/nikke/fullbody/idoll-sun.png'},
    {id: 'cocoa', name: 'Cocoa', image: 'images/nikke/fullbody/cocoa.png'},
    {id: 'soda', name: 'Soda', image: 'images/nikke/fullbody/soda.png'},
    {id: 'mast', name: 'Mast', image: 'images/nikke/fullbody/mast.png', imageScale: 1.10},
    {id: 'anchor', name: 'Anchor', image: 'images/nikke/fullbody/anchor.png'},
    {id: 'helm', name: 'Helm', image: 'images/nikke/fullbody/helm.png', imageScale: 1.10, imageY: '5%', imageX: '2%'},
    {id: 'helm-aquamarine', name: 'Helm: Aquamarine', image: 'images/nikke/fullbody/helm-aquamarine.png', imageScale: 1.02},
    {id: 'nero', name: 'Nero', image: 'images/nikke/fullbody/nero.png'},
    {id: 'biscuit', name: 'Biscuit', image: 'images/nikke/fullbody/biscuit.png'},
    {id: 'rei', name: 'Rei', image: 'images/nikke/fullbody/rei.png', imageScale: 1.18},
    {id: 'guilty', name: 'Guilty', image: 'images/nikke/fullbody/guilty.png'},
    {id: 'sin', name: 'Sin', image: 'images/nikke/fullbody/sin.png'},
    {id: 'quency', name: 'Quency', image: 'images/nikke/fullbody/quency.png'},
    {id: 'noise', name: 'Noise', image: 'images/nikke/fullbody/noise.png'},
    {id: 'volume', name: 'Volume', image: 'images/nikke/fullbody/volume.png', imageScale: 1.08},
    {id: 'aria', name: 'Aria', image: 'images/nikke/fullbody/aria.png'},
    {id: 'makima', name: 'Makima', image: 'images/nikke/fullbody/makima.png'},

    {id: 'mica-snow-buddy', name: 'Mica: Snow Buddy', image: 'images/nikke/fullbody/mica-snow-buddy.png'},
    {id: 'ludmilla-winter-owner', name: 'Ludmilla: Winter Owner', image: 'images/nikke/fullbody/ludmilla-winter-owner.png', imageScale: 1.05, imageX: '6%', imageY: '-2%'},
    {id: 'alice-wonderland-bunny', name: 'Alice: Wonderland Bunny', image: 'images/nikke/fullbody/alice-wonderland-bunny.png'},
    {id: 'snow-white-innocent-days', name: 'Snow White: Innocent Days', image: 'images/nikke/fullbody/snow-white-innocent-days.png'},
    {id: 'scarlet-black-shadow', name: 'Scarlet: Black Shadow', image: 'images/nikke/fullbody/scarlet-black-shadow.png'},
    {id: 'rapunzel-pure-grace', name: 'Rapunzel: Pure Grace', image: 'images/nikke/fullbody/rapunzel-pure-grace.png'},
    {id: 'ade', name: 'Ade', image: 'images/nikke/fullbody/ade.png', imageScale: 1.14, imageX: '3%', imageY: '-3%'},
    {id: 'privaty-unkind-maid', name: 'Privaty: Unkind Maid', image: 'images/nikke/fullbody/privaty-unkind-maid.png'},
    {id: 'soda-twinkling-bunny', name: 'Soda: Twinkling Bunny', image: 'images/nikke/fullbody/soda-twinkling-bunny.png'},
    {id: 'marciana', name: 'Marciana', image: 'images/nikke/fullbody/marciana.png'},
    {id: 'crown', name: 'Crown', image: 'images/nikke/fullbody/crown.png', imageScale: 1.34, imageX: '-4%'},
    {id: 'mast-romantic-maid', name: 'Mast: Romantic Maid', image: 'images/nikke/fullbody/mast-romantic-maid.png'},
    {id: 'anchor-innocent-maid', name: 'Anchor: Innocent Maid', image: 'images/nikke/fullbody/anchor-innocent-maid.png', imageScale: 1.15},
    {id: 'leona', name: 'Leona', image: 'images/nikke/fullbody/leona.png'},
    {id: 'zwei', name: 'Zwei', image: 'images/nikke/fullbody/zwei.png'},
    {id: 'ein', name: 'Ein', image: 'images/nikke/fullbody/ein.png', imageScale: 1.26, imageX: '9%', imageY: '-1%'},
    {id: 'quency-escape-queen', name: 'Quency: Escape Queen', image: 'images/nikke/fullbody/quency-escape-queen.png'},
    {id: 'flora', name: 'Flora', image: 'images/nikke/fullbody/flora.png', imageScale: 1.15},
    {id: 'trina', name: 'Trina', image: 'images/nikke/fullbody/trina.png'},
    {id: 'naga', name: 'Naga', image: 'images/nikke/fullbody/naga.png'},

    {id: 'rapi-red-hood', name: 'Rapi: Red Hood', image: 'images/nikke/fullbody/rapi-red-hood.png'},
    {id: 'anis-star', name: 'Anis: Star', image: 'images/nikke/fullbody/anis-star.png', imageScale: 1.08},
    {id: 'neon-vision-eye', name: 'Neon: Vision Eye', image: 'images/nikke/fullbody/neon-vision-eye.png', imageScale: 1.50, imageY: '1%'},
    {id: 'delta-ninja-thief', name: 'Delta: Ninja Thief', image: 'images/nikke/fullbody/delta-ninja-thief.png', imageScale: 1.20, imageX: '4%', imageY: '-2%'},
    {id: 'quiry', name: 'Quiry', image: 'images/nikke/fullbody/quiry.png'},
    {id: 'k', name: 'K', image: 'images/nikke/fullbody/k.png'},
    {id: 'd-killer-wife', name: 'D: Killer Wife', image: 'images/nikke/fullbody/d-killer-wife.png'},
    {id: 'soline-frost-ticket', name: 'Soline: Frost Ticket', image: 'images/nikke/fullbody/soline-frost-ticket.png'},
    {id: 'diesel-winter-sweets', name: 'Diesel: Winter Sweets', image: 'images/nikke/fullbody/diesel-winter-sweets.png'},
    {id: 'emma-tactical-upgrade', name: 'Emma: Tactical Upgrade', image: 'images/nikke/fullbody/emma-tactical-upgrade.png', imageScale: 1.08, imageX: '3%'},
    {id: 'vesti-tactical-upgrade', name: 'Vesti: Tactical Upgrade', image: 'images/nikke/fullbody/vesti-tactical-upgrade.png', imageScale: 1.34, imageX: '12%', imageY: '-2%'},
    {id: 'eunhwa-tactical-upgrade', name: 'Eunhwa: Tactical Upgrade', image: 'images/nikke/fullbody/eunhwa-tactical-upgrade.png'},
    {id: 'laplace-ultimate-hero', name: 'Laplace: Ultimate Hero', image: 'images/nikke/fullbody/laplace-ultimate-hero.png', imageScale: 1.12, imageX: '4%'},
    {id: 'maxwell-ordinary-mechanic', name: 'Maxwell: Ordinary Mechanic', image: 'images/nikke/fullbody/maxwell-ordinary-mechanic.png', imageScale: 1.08},
    {id: 'eh', name: 'E.H.', image: 'images/nikke/fullbody/eh.png'},
    {id: 'milk-blooming-bunny', name: 'Milk: Blooming Bunny', image: 'images/nikke/fullbody/milk-blooming-bunny.png'},
    {id: 'mihara-bonding-chain', name: 'Mihara: Bonding Chain', image: 'images/nikke/fullbody/mihara-bonding-chain.png', imageScale: 1.06, imageY: '7%'},
    {id: 'guillotine-winter-slayer', name: 'Guillotine: Winter Slayer', image: 'images/nikke/fullbody/guillotine-winter-slayer.png'},
    {id: 'maiden-ice-rose', name: 'Maiden: Ice Rose', image: 'images/nikke/fullbody/maiden-ice-rose.png', imageScale: 1.01},
    {id: 'tove', name: 'Tove', image: 'images/nikke/fullbody/tove.png'},

    {id: '2b', name: '2B', image: 'images/nikke/fullbody/2b.png', imageScale: 1.20, imageX: '-5%'},
    {id: 'a2', name: 'A2', image: 'images/nikke/fullbody/a2.png'},
    {id: 'ada-wong', name: 'Ada Wong', image: 'images/nikke/fullbody/ada-wong.png'},
    {id: 'ade-agent-bunny', name: 'Ade: Agent Bunny', image: 'images/nikke/fullbody/ade-agent-bunny.png'},
    {id: 'arcana', name: 'Arcana', image: 'images/nikke/fullbody/arcana.png'},
    {id: 'arcana-fortune-mate', name: 'Arcana: Fortune Mate', image: 'images/nikke/fullbody/arcana-fortune-mate.png'},
    {id: 'ark-ranger-black', name: 'Ark Ranger Black', image: 'images/nikke/fullbody/ark-ranger-black.png'},
    {id: 'asuka-shikinami-langley', name: 'Asuka Shikinami Langley', image: 'images/nikke/fullbody/asuka-shikinami-langley.png'},
    {id: 'asuka-shikinami-langley-wille', name: 'Asuka Shikinami Langley: Wille', image: 'images/nikke/fullbody/asuka-shikinami-langley-wille.png', imageScale: 1.15, imageY: '0%'},
    {id: 'avistar', name: 'Avistar', image: 'images/nikke/fullbody/avistar.png', imageScale: 1.45},
    {id: 'bay', name: 'Bay', image: 'images/nikke/fullbody/bay.png'},
    {id: 'bready', name: 'Bready', image: 'images/nikke/fullbody/bready.png'},
    {id: 'brid-silent-track', name: 'Brid: Silent Track', image: 'images/nikke/fullbody/brid-silent-track.png'},
    {id: 'chime', name: 'Chime', image: 'images/nikke/fullbody/chime.png'},
    {id: 'chisato-nishikigi', name: 'Chisato Nishikigi', image: 'images/nikke/fullbody/chisato-nishikigi.png'},
    {id: 'cinderella', name: 'Cinderella', image: 'images/nikke/fullbody/cinderella.png', imageScale: 1.55, imageX: '10%', imageY: '0%'},
    {id: 'cinderella-crystal-wave', name: 'Cinderella: Crystal Wave', image: 'images/nikke/fullbody/cinderella-crystal-wave.png'},
    {id: 'claire-redfield', name: 'Claire Redfield', image: 'images/nikke/fullbody/claire-redfield.png'},
    {id: 'clay', name: 'Clay', image: 'images/nikke/fullbody/clay.png'},
    {id: 'crust', name: 'Crust', image: 'images/nikke/fullbody/crust.png'},

    {id: 'dorothy-serendipity', name: 'Dorothy: Serendipity', image: 'images/nikke/fullbody/dorothy-serendipity.png', imageScale: 1.10},
    {id: 'elegg', name: 'Elegg', image: 'images/nikke/fullbody/elegg.png'},
    {id: 'elegg-boom-and-shock', name: 'Elegg: Boom and Shock', image: 'images/nikke/fullbody/elegg-boom-and-shock.png', imageScale: 1.05},
    {id: 'emilia', name: 'Emilia', image: 'images/nikke/fullbody/emilia.png', imageScale: 1.05},
    {id: 'eve', name: 'EVE', image: 'images/nikke/fullbody/eve.png'},
    {id: 'grave', name: 'Grave', image: 'images/nikke/fullbody/grave.png'},
    {id: 'himeno', name: 'Himeno', image: 'images/nikke/fullbody/himeno.png'},
    {id: 'jill-valentine', name: 'Jill Valentine', image: 'images/nikke/fullbody/jill-valentine.png'},
    {id: 'kilo', name: 'Kilo', image: 'images/nikke/fullbody/kilo.png'},
    {id: 'kurumi', name: 'Kurumi', image: 'images/nikke/fullbody/kurumi.png'},
    {id: 'label', name: 'Label', image: 'images/nikke/fullbody/label.png', imageScale: 1.05},
    {id: 'liberalio', name: 'Liberalio', image: 'images/nikke/fullbody/liberalio.png', imageScale: 1.40, imageY: '6%'},
    {id: 'lily', name: 'Lily', image: 'images/nikke/fullbody/lily.png'},
    {id: 'mana', name: 'Mana', image: 'images/nikke/fullbody/mana.png'},
    {id: 'marciana-marine-study', name: 'Marciana: Marine Study', image: 'images/nikke/fullbody/marciana-marine-study.png'},
    {id: 'mari-makinami-illustrious', name: 'Mari Makinami Illustrious', image: 'images/nikke/fullbody/mari-makinami-illustrious.png'},
    {id: 'mint', name: 'Mint', image: 'images/nikke/fullbody/mint.png'},
    {id: 'misato-katsuragi', name: 'Misato Katsuragi', image: 'images/nikke/fullbody/misato-katsuragi.png'},
    {id: 'moran', name: 'Moran', image: 'images/nikke/fullbody/moran.png'},
    {id: 'mori', name: 'Mori', image: 'images/nikke/fullbody/mori.png'},

    {id: 'nayuta', name: 'Nayuta', image: 'images/nikke/fullbody/nayuta.png', imageScale: 1.05},
    {id: 'pascal', name: 'Pascal', image: 'images/nikke/fullbody/pascal.png'},
    {id: 'phantom', name: 'Phantom', image: 'images/nikke/fullbody/phantom.png', imageScale: 1.05},
    {id: 'power', name: 'Power', image: 'images/nikke/fullbody/power.png'},
    {id: 'prika', name: 'Prika', image: 'images/nikke/fullbody/prika.png'},
    {id: 'ram', name: 'Ram', image: 'images/nikke/fullbody/ram.png'},
    {id: 'raven', name: 'Raven', image: 'images/nikke/fullbody/raven.png', imageScale: 1.25},
    {id: 'red-hood', name: 'Red Hood', image: 'images/nikke/fullbody/red-hood.png', imageScale: 1.10},
    {id: 'rei-ayanami', name: 'Rei Ayanami', image: 'images/nikke/fullbody/rei-ayanami.png'},
    {id: 'rei-ayanami-tentative-name', name: 'Rei Ayanami (Tentative Name)', image: 'images/nikke/fullbody/rei-ayanami-tentative-name.png'},
    {id: 'rem', name: 'Rem', image: 'images/nikke/fullbody/rem.png'},
    {id: 'rosanna-chic-ocean', name: 'Rosanna: Chic Ocean', image: 'images/nikke/fullbody/rosanna-chic-ocean.png'},
    {id: 'rouge', name: 'Rouge', image: 'images/nikke/fullbody/rouge.png', imageScale: 1.05},
    {id: 'sakura-bloom-in-summer', name: 'Sakura: Bloom in Summer', image: 'images/nikke/fullbody/sakura-bloom-in-summer.png', imageScale: 1.15},
    {id: 'sakura-suzuhara', name: 'Sakura Suzuhara', image: 'images/nikke/fullbody/sakura-suzuhara.png'},
    {id: 'siren', name: 'Little Mermaid (Siren)', image: 'images/nikke/fullbody/siren.png', imageScale: 1.25},
    {id: 'snow-crane', name: 'Snow Crane', image: 'images/nikke/fullbody/snow-crane.png', imageScale: 1.25},
    {id: 'snow-white-heavy-arms', name: 'Snow White: Heavy Arms', image: 'images/nikke/fullbody/snow-white-heavy-arms.png', imageScale: 1.30, imageX: '-10%'},
    {id: 'sora', name: 'Sora', image: 'images/nikke/fullbody/sora.png'},
    {id: 'tia', name: 'Tia', image: 'images/nikke/fullbody/tia.png', imageScale: 1.15},
];
