var items = [
    {id: 'rapi', name: 'Rapi', image: 'images/nikke/fullbody/rapi.png'},
    {id: 'anis', name: 'Anis', image: 'images/nikke/fullbody/anis.png'},
    {id: 'neon', name: 'Neon', image: 'images/nikke/fullbody/neon.png'},

    {id: 'delta', name: 'Delta', image: 'images/nikke/fullbody/delta.png'},
    {id: 'signal', name: 'Signal', image: 'images/nikke/fullbody/signal.png'},
    {id: 'poli', name: 'Poli', image: 'images/nikke/fullbody/poli.png'},
    {id: 'miranda', name: 'Miranda', image: 'images/nikke/fullbody/miranda.png'},
    {id: 'd', name: 'D', image: 'images/nikke/fullbody/d.png'},

    {id: 'belorta', name: 'Belorta', image: 'images/nikke/fullbody/belorta.png'},
    {id: 'mica', name: 'Mica', image: 'images/nikke/fullbody/mica.png'},
    {id: 'brid', name: 'Brid', image: 'images/nikke/fullbody/brid.png'},
    {id: 'soline', name: 'Soline', image: 'images/nikke/fullbody/soline.png'},
    {id: 'diesel', name: 'Diesel', image: 'images/nikke/fullbody/diesel.png'},

    {id: 'centi', name: 'Centi', image: 'images/nikke/fullbody/centi.png'},
    {id: 'liter', name: 'Liter', image: 'images/nikke/fullbody/liter.png'},
    {id: 'emma', name: 'Emma', image: 'images/nikke/fullbody/emma.png'},
    {id: 'vesti', name: 'Vesti', image: 'images/nikke/fullbody/vesti.png'},
    {id: 'eunhwa', name: 'Eunhwa', image: 'images/nikke/fullbody/eunhwa.png'},

    {id: 'laplace', name: 'Laplace', image: 'images/nikke/fullbody/laplace.png'},
    {id: 'drake', name: 'Drake', image: 'images/nikke/fullbody/drake.png'},
    {id: 'maxwell', name: 'Maxwell', image: 'images/nikke/fullbody/maxwell.png'},
    {id: 'crow', name: 'Crow', image: 'images/nikke/fullbody/crow.png'},
    {id: 'jackal', name: 'Jackal', image: 'images/nikke/fullbody/jackal.png'},
    {id: 'viper', name: 'Viper', image: 'images/nikke/fullbody/viper.png'},
    {id: 'n102', name: 'N102', image: 'images/nikke/fullbody/n102.png'},
    {id: 'anne-miracle-fairy', name: 'Anne: Miracle Fairy', image: 'images/nikke/fullbody/anne-miracle-fairy.png'},
    {id: 'mary', name: 'Mary', image: 'images/nikke/fullbody/mary.png'},
    {id: 'pepper', name: 'Pepper', image: 'images/nikke/fullbody/pepper.png'},
    {id: 'mary-bay-goddess', name: 'Mary: Bay Goddess', image: 'images/nikke/fullbody/mary-bay-goddess.png'},
    {id: 'sugar', name: 'Sugar', image: 'images/nikke/fullbody/sugar.png'},
    {id: 'milk', name: 'Milk', image: 'images/nikke/fullbody/milk.png'},
    {id: 'frima', name: 'Frima', image: 'images/nikke/fullbody/frima.png'},
    {id: 'julia', name: 'Julia', image: 'images/nikke/fullbody/julia.png'},

    {id: 'yuni', name: 'Yuni', image: 'images/nikke/fullbody/yuni.png'},
    {id: 'mihara', name: 'Mihara', image: 'images/nikke/fullbody/mihara.png'},
    {id: 'privaty', name: 'Privaty', image: 'images/nikke/fullbody/privaty.png'},
    {id: 'yulha', name: 'Yulha', image: 'images/nikke/fullbody/yulha.png'},
    {id: 'admi', name: 'Admi', image: 'images/nikke/fullbody/admi.png'},
    {id: 'guillotine', name: 'Guillotine', image: 'images/nikke/fullbody/guillotine.png'},
    {id: 'maiden', name: 'Maiden', image: 'images/nikke/fullbody/maiden.png'},
    {id: 'ludmilla', name: 'Ludmilla', image: 'images/nikke/fullbody/ludmilla.png'},
    {id: 'alice', name: 'Alice', image: 'images/nikke/fullbody/alice.png'},
    {id: 'neve', name: 'Neve', image: 'images/nikke/fullbody/neve.png'},
    {id: 'rupee', name: 'Rupee', image: 'images/nikke/fullbody/rupee.png'},
    {id: 'yan', name: 'Yan', image: 'images/nikke/fullbody/yan.png'},
    {id: 'dolla', name: 'Dolla', image: 'images/nikke/fullbody/dolla.png'},
    {id: 'rupee-winter-shopper', name: 'Rupee: Winter Shopper', image: 'images/nikke/fullbody/rupee-winter-shopper.png'},
    {id: 'exia', name: 'Exia', image: 'images/nikke/fullbody/exia.png'},
    {id: 'novel', name: 'Novel', image: 'images/nikke/fullbody/novel.png'},
    {id: 'snow-white', name: 'Snow White', image: 'images/nikke/fullbody/snow-white.png'},
    {id: 'rapunzel', name: 'Rapunzel', image: 'images/nikke/fullbody/rapunzel.png'},
    {id: 'scarlet', name: 'Scarlet', image: 'images/nikke/fullbody/scarlet.png'},
    {id: 'harran', name: 'Harran', image: 'images/nikke/fullbody/harran.png'}
];
